### ISSUE TITLE
Choose at which thread to start iterating in cfg

### ISSUE THREAD

**Issue by travis-mcginley** [fhoekstra/thread_switcher#2]
The ability to choose which thread to start the iteration would allow for more efficient testing of thread groups.

**Comment by travis-mcginley** [comment]
Modified base code and created a pull request for this feature.

**Comment by fhoekstra** [comment]
Added in: [this commit](https://github.com/fhoekstra/thread_switcher/commit/28ad74f424871923148b39f7f6a5e5dcfe18dcd9)

**Comment by fhoekstra** [comment]
Thanks again for your feature request and example code! It helped a lot to guide me towards cleaner code for this repository!
