### ISSUE TITLE
Align with wall clock

### ISSUE THREAD

**Issue by metalshark** [fhoekstra/thread_switcher#4]
Option to run on a schedule based on wall clock time. Prime95 reports errors in `MMM dd hh:mm` format, even if switching every 60 seconds to be able to identify which core failed from the Prime95 messages there's a potential for wall clock misalignment and drift over time. Allow a secondary option in minutes (1 minute, 2 minutes, etc) and align the switching with the wall clock switch between minutes to identify which core has a failure in Prime95).

Did some crude butchering for my purpose for now, but it would useful for those tuning curve optimiser values.
```python
for thread in get_infinite_iterator(thread_list):
    sleeptime = 60 - (dt.utcnow().second + (dt.utcnow().microsecond/1000000))
    time.sleep(sleeptime)
    log_starting_thread(thread)
    run('Powershell "ForEach($PROCESS in'
        + f' GET-PROCESS {cfg["process_to_switch"]})'
        + ' { $PROCESS.ProcessorAffinity=' + thread.affinity_mask
        + '}"')
```

**Comment by fhoekstra** [comment]
Great remark and thanks for the example code! I'll try my hand at a configurable option soon. Hopefully tomorrow!

In the meantime, please consider running prime95 for longer on one thread at a time. I got some advice [here](https://www.reddit.com/r/Amd/comments/koytwe/curve_optimizer_percore_stability_test_tool/gnmzloi?utm_medium=android_app&utm_source=share&context=3) that seems to indicate that a failure may be delayed by a bit, so switching every couple of seconds may not be good default behaviour anyways.

I will also look at incorporating the suggestion from that comment to run prime95 on both threads on a physical core.

**Comment by fhoekstra** [comment]
Added both features in
[c45fa93](https://github.com/fhoekstra/thread_switcher/commit/c45fa93ee6596766ccf159d7784b88ca9b061072)
