### ISSUE TITLE
This tool wont work for me

### ISSUE THREAD

**Issue by FumeroBR** [fhoekstra/thread_switcher#5]
Nevermind, i already solved the problem.

**Comment by fhoekstra** [comment]
Hi @FumeroBR, thanks for sharing your problem.

**Could you please mention how you resolved it?** This can help others having the same problem and gives me an opportunity to improve the documentation or setup process.

**Comment by FumeroBR** [comment]
> Hi @FumeroBR, thanks for sharing your problem.
> 
> **Could you please mention how you resolved it?** This can help others having the same problem and gives me an opportunity to improve the documentation or setup process.


Hi, the problem is the tutorial mention that i have to do a double click in the run.bat file for the tool work but for me the tool finally worked when i opened the main.py file.

**Comment by fhoekstra** [comment]
Thanks! Did you install Python from python.org or Windows 10 Microsoft Store?
You are running Windows 10, I presume?

**Comment by FumeroBR** [comment]
> Thanks! Did you install Python from python.org or Windows 10 Microsoft Store?
> You are running Windows 10, I presume?

I installed python from python.org and i am running windows 10 home edition.

**Comment by fhoekstra** [comment]
Thanks for your help, I've added that way of running the tool to the readme!
